app = 'insta-bot'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[processes]
  app = "python main.py"

# HTTP service yo'q, shuning uchun "instance refused" xatosi chiqmaydi
# Avtomatik o'chishni to'xtatish uchun maxsus sozlama:
[experimental]
  auto_build = true

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'

[env]
  PYTHONUNBUFFERED = "1"
  
