app = "insta-bot"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  # Bot 24/7 ishlashi uchun bularni shunday qiling:
  auto_stop_machines = false 
  auto_start_machines = true
  min_machines_running = 1 

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1