app = "my-insta-bot" # Ilova nomini xohlagancha o'zgartiring (faqat kichik harflar va chiziqlar)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80
    [services.ports.http_options]

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
    [services.ports.http_options]
    
