# data/hadis_data.py
HADISLAR = [
    {
        "arabic": "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ",
        "latin": "Innamal a’malu bin-niyyat.",
        "cyrillic": "Иннамал аъмалу бин-нийят.",
        "uzbek": "Albatta, amallar niyatlarga bog'liqdir."
    },
    {
        "arabic": "الدِّينُ النَّصِيحَةُ",
        "latin": "Ad-diinu-n-nasiihah.",
        "ad": "Ад-дийну-н-насийҳа.",
        "uzbek": "Din nasihatdir (samimiylikdir)."
    },
     {"arabic": "الْجَنَّةُ تَحْتَ أَقْدَامِ الأُمَّهَاتِ", "latin": "Al-jannatu tahta aqdaamil ummahaat.", "cyrillic": "Ал-жаннату таҳта ақдаамил уммаҳаат.", "uzbek": "Jannat onalar qadami ostidadir."},
    {"arabic": "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ", "latin": "Xoyrukum man ta’allamal Qur’ana va ‘allamahu.", "cyrillic": "Хойрукум ман таъалламал Қуръана ва ъалламаҳу.", "uzbek": "Sizlarning eng yaxshilaringiz Qur'onni o'rgangan va o'rgatganlaringizdir."},
    {"arabic": "مَنْ صَمَتَ نَجَا", "latin": "Man somata naja.", "cyrillic": "Ман сомата нажа.", "uzbek": "Kim sukut saqlasa, najot topadi."},
    {"arabic": "الْحَيَاءُ مِنَ الإِيمَانِ", "latin": "Al-hayaau minal iimaan.", "cyrillic": "Ал-ҳаяау минал иймаан.", "uzbek": "Hayo imondandir."},
    {"arabic": "اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ", "latin": "Ittaqillaha haysumaa kunta.", "cyrillic": "Иттақиллаҳа ҳайсумаа кунта.", "uzbek": "Qayerda bo'lsang ham Allohdan qo'rq."},
    {"arabic": "كُلُّ ابْنِ آدَمَ خَطَّاءٌ", "latin": "Kullu ibni aadama xottoo-un.", "cyrillic": "Куллу ибни аадама хоттоо-ун.", "uzbek": "Barcha odam bolasi xato qiluvchidir."},
    {"arabic": "اَلصَّبْرُ ضِيَاءٌ", "latin": "As-sobru diyaa-un.", "cyrillic": "Ас-собру дияа-ун.", "uzbek": "Sabr ziyodir."},
    {"arabic": "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ صَدَقَةٌ", "latin": "Tabassumuka fii vajhi axiika sodaqotun.", "cyrillic": "Табассумука фий важҳи ахийка содақотун.", "uzbek": "Birodaringga tabassum qilishing sadaqadir."},
    {"arabic": "اَلْمُؤْمِنُ مِرْآةُ الْمُؤْمِنِ", "latin": "Al-mu'minu mir'atul mu'min.", "cyrillic": "Ал-мўмину мир-атул мўмин.", "uzbek": "Mo'min mo'minning ko'zgusidir."},
    {"arabic": "لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ", "latin": "Laa yu'minu ahadukum hattaa yuhibba li-axiihi maa yuhibbu li-nafsihi.", "cyrillic": "Лаа юъмину аҳадукум ҳаттаа юҳибба ли-ахийҳи маа юҳиббу ли-нафсиҳи.", "uzbek": "Sizlardan birortangiz o'ziga yaxshi ko'rgan narsani birodariga ham ravo ko'rmagunicha komil mo'min bo'la olmaydi."},
    {"arabic": "اَلصِّدْقُ يُنْجِي", "latin": "As-sidqu yunji.", "cyrillic": "Ас-сидқу юнжий.", "uzbek": "Rostgo'ylik najot beradi."},
    {"arabic": "مَنْ لاَ يَرْحَمُ لاَ يُرْحَمُ", "latin": "Man laa yarhamu laa yurham.", "cyrillic": "Ман лаа ярҳаму лаа юрҳам.", "uzbek": "Rahm qilmaganga rahm qilinmaydi."},
    {"arabic": "يَسِّرُوا وَلاَ تُعَسِّرُوا", "latin": "Yassiruu va laa tu'assiruu.", "cyrillic": "Яссируу ва лаа туъассируу.", "uzbek": "Osonlashtiringlar, qiyinlashtirmanglar."},
    {"arabic": "اَلْعِلْمُ حَيَاةُ الإِسْلاَمِ", "latin": "Al-'ilmu hayaatul Islaam.", "cyrillic": "Ал-илму ҳаяатул Ислаам.", "uzbek": "Ilm Islomning hayotidir."},
    {"arabic": "اَلْوَقْتُ كَالسَّيْفِ", "latin": "Al-waqtu kas-sayf.", "cyrillic": "Ал-вақту кас-сайф.", "uzbek": "Vaqt qilich kabidir (kesadi)."},
    {"arabic": "خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ", "latin": "Xoyrun-naasi anfa'uhum lin-naas.", "cyrillic": "Хойрун-нааси анфаъуҳум лин-наас.", "uzbek": "Odamlarning eng yaxshisi odamlarga foydasi tegadiganidir."},
    {"arabic": "اَلنَّظَافَةُ مِنَ الإِيمَانِ", "latin": "An-nazofatu minal iimaan.", "cyrillic": "Ан-назофату минал иймаан.", "uzbek": "Poklik imondandir."},
    {"arabic": "لاَ تَغْضَبْ", "latin": "Laa taghdob.", "cyrillic": "Лаа тағдоб.", "uzbek": "G'azablanma."},
    {"arabic": "مَنْ غَشَّنَا فَلَيْسَ مِنَّا", "latin": "Man ghash-shanaa falaysa minnaa.", "cyrillic": "Ман ғашшанаа фалайса миннаа.", "uzbek": "Kim bizni aldasa, u bizdan emas."},
    {"arabic": "اَلْيَدُ الْعُلْيَا خَيْرٌ مِنَ الْيَدِ السُّفْلَى", "latin": "Al-yadul 'ulyaa xoyrun minal yadis-suflaa.", "cyrillic": "Ал-ядул ъуляа хойрун минал ядис-суфлаа.", "uzbek": "Yuqori (beruvchi) qo'l quyi (oluvchi) qo'ldan yaxshiroqdir."},
    {"arabic": "اَلْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ", "latin": "Al-muslimu man salimal muslimuuna min lisaanihi va yadihi.", "cyrillic": "Ал-муслиму ман салимал муслимууна мин лисааниҳи ва ядиҳи.", "uzbek": "Musulmon kishi – tilidan va qo'lidan musulmonlar omonlik topgan kishidir."},
    {"arabic": "اَلصَّلاَةُ عِمَادُ الدِّينِ", "latin": "As-solaatu 'imaadud-diin.", "cyrillic": "Ас-солаату ъимаадуд-дийн.", "uzbek": "Namoz dinning ustunidir."},
    {"arabic": "اَللَّهُ جَمِيلٌ يُحِبُّ الْجَمَالَ", "latin": "Allohu jamiilun yuhibbul jamaal.", "cyrillic": "Аллоҳу жамийлун юҳиббул жамаал.", "uzbek": "Alloh go'zaldir, go'zallikni sevar."},
    {"arabic": "كُلُّ مَعْرُوفٍ صَدَقَةٌ", "latin": "Kullu ma'ruufin sodaqotun.", "cyrillic": "Куллу маърувфин содақотун.", "uzbek": "Har bir yaxshilik sadaqadir."},
    {"arabic": "اَلْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ", "latin": "Al-kalimatut-toyyibatu sodaqotun.", "cyrillic": "Ал-калиматут-тоййибату содақотун.", "uzbek": "Yaxshi so'z sadaqadir."},
    {"arabic": "اِتَّقُوا النَّارَ وَلَوْ بِشِقِّ تَمْرَةٍ", "latin": "Ittaqun-naara va lav bishiqqi tamrah.", "cyrillic": "Иттақун-наара ва лав бишиққи тамраҳ.", "uzbek": "Yarimta xurmo bilan bo'lsa ham o'zingizni do'zaxdan saqlang."},
    {"arabic": "لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ", "latin": "Laa havla va laa quvvata illaa billaah.", "cyrillic": "Лаа ҳавла ва лаа қуввата иллаа биллааҳ.", "uzbek": "Allohdan o'zga kuch va quvvat yo'qdir."},
    {"arabic": "اَلرِّضَا بِالْقَضَاءِ", "latin": "Ar-rido bil qodoo-i.", "cyrillic": "Ар-ризо бил қозо-и.", "uzbek": "Qazoi-qadarga rozi bo'lish (imondandir)."},
    {"arabic": "اَلْعِلْمُ صَيْدٌ وَالْكِتَابَةُ قَيْدٌ", "latin": "Al-'ilmu soydun val-kitaabatu qoydun.", "cyrillic": "Ал-илму сойдун вал-китаабату қойдун.", "uzbek": "Ilm ovdir, yozib qo'yish esa uni bog'lab qo'yishdir."},
    {"arabic": "مَنْ جَدَّ وَجَدَ", "latin": "Man jadda vajad.", "cyrillic": "Ман жадда важад.", "uzbek": "Kim qidirsa, topadi (harakat qilgan yetadi)."},
    {"arabic": "اَلصَّبْرُ مِفْتَاحُ الْفَرَجِ", "latin": "As-sobru miftaahul faroj.", "cyrillic": "Ас-собру мифтааҳул фараж.", "uzbek": "Sabr yengillik kalitidir."},
    {"arabic": "لاَ يُلْدَغُ الْمُؤْمِنُ مِنْ جُحْرٍ وَاحِدٍ مَرَّتَيْنِ", "latin": "Laa yuldaghul mu'minu min juhrin vaahidin marratayn.", "cyrillic": "Лаа юлдағул мўмину мин жуҳрин вааҳидин марратайни.", "uzbek": "Mo'min kishi bir teshikdan ikki marta chaqilmaydi (bir xatoga ikki marta yo'l qo'ymaydi)."},
    {"arabic": "اَلْحَيَاءُ شُعْبَةٌ مِنَ الإِيمَانِ", "latin": "Al-hayaau shu'batun minal iimaan.", "cyrillic": "Ал-ҳаяау шуъбатун минал иймаан.", "uzbek": "Hayo imonning bir shoxchasidir."},
    {"arabic": "تَعَاوَنُوا عَلَى الْبِرِّ وَالتَّقْوَى", "latin": "Ta'aavanuu 'alal birri vat-taqvaa.", "cyrillic": "Таъаавануу ъалал бирри ват-тақваа.", "uzbek": "Yaxshilik va taqvo yo'lida bir-biringizga yordam bering."},
    {"arabic": "قُلِ الْحَقَّ وَلَوْ كَانَ مُرًّا", "latin": "Qulil haqqa va lav kaana murran.", "cyrillic": "Қулил ҳаққа ва лав каана мурран.", "uzbek": "Achiq bo'lsa ham haqiqatni gapir."},
    {"arabic": "اَلْيَدُ الَّتِي تُعْطِي خَيْرٌ مِنَ الْيَدِ الَّتِي تَأْخُذُ", "latin": "Al-yadullatii tu'tii xoyrun minal yadillatii ta'xuz.", "cyrillic": "Ал-ядуллатий туътий хойрун минал ядиллатий таъхуз.", "uzbek": "Beruvchi qo'l oluvchi qo'ldan yaxshiroqdir."},
    {"arabic": "اَلدُّعَاءُ سِلاَحُ الْمُؤْمِنِ", "latin": "Ad-du'aa-u silaahul mu'min.", "cyrillic": "Ад-дуъаа-у силааҳул мўмин.", "uzbek": "Duo mo'minning qurolidir."},
    {"arabic": "اَلْخَيْرُ فِيمَا اخْتَارَهُ اللَّهُ", "latin": "Al-xoyru fiimaa ixtaarohulloh.", "cyrillic": "Ал-хойру фиймаа ихтаароҳуллоҳ.", "uzbek": "Yaxshilik Alloh ixtiyor qilgan narsadadir."},
    {"arabic": "مَنْ لَمْ يَشْكُرِ النَّاسَ لَمْ يَشْكُرِ اللَّهَ", "latin": "Man lam yashkurin-naasa lam yashkurillaah.", "cyrillic": "Ман лам яшкурин-нааса лам яшкуриллааҳ.", "uzbek": "Odamlarga shukr qilmagan kishi Allohga ham shukr qilmagan bo'ladi."},
    {"arabic": "اَلصَّبْرُ عِنْدَ الصَّدْمَةِ الأُولَى", "latin": "As-sobru 'indas-sodmatil uulaa.", "cyrillic": "Ас-собру ъиндас-содматил уулаа.", "uzbek": "Sabr – musibatning dastlabki lahzasidagi sabrdir."},
    {"arabic": "اَلْقَنَاعَةُ كَنْزٌ لاَ يَفْنَى", "latin": "Al-qana'atu kanzun laa yafnaa.", "cyrillic": "Ал-қанааъату канзун лаа яфнаа.", "uzbek": "Qanoat tugamas xazinadir."},
    {"arabic": "اَلْعِلْمُ نُورٌ", "latin": "Al-'ilmu nuur.", "cyrillic": "Ал-илму нуур.", "uzbek": "Ilm nurdir."},
    {"arabic": "اِعْمَلْ لِدُنْيَاكَ كَأَنَّكَ تَعِيشُ أَبَدًا وَاعْمَلْ لآخِرَتِكَ كَأَنَّكَ تَمُوتُ غَدًا", "latin": "I'mal lidunyaaka ka-annaka ta'iishu abadan va'mal li-aaxirotika ka-annaka tamuutu ghodan.", "cyrillic": "Иъмал лидуняака ка-аннака таъийшу абадан ваъмал ли-аахиротика ка-аннака тамууту ғодан.", "uzbek": "Dunyoing uchun xuddi abadiy yashaydigandek, oxirating uchun esa xuddi ertaga o'ladigandek amal qil."},
    {"arabic": "مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ", "latin": "Man salaka toriiqon yaltamisu fiihi 'ilman sahhalallohu lahu toriiqon ilal jannah.", "cyrillic": "Ман салака торийқон ялтамису фийҳи ъилман саҳҳаллаҳу лаҳу торийқон илал жаннаҳ.", "uzbek": "Kim ilm talab qilib yo'lga chiqsa, Alloh unga jannat yo'lini oson qiladi."},
    {"arabic": "اَلْأَدَبُ فَوْقَ الْعِلْمِ", "latin": "Al-adabu favqol 'ilm.", "cyrillic": "Ал-адабу фавқол ъилм.", "uzbek": "Odob ilmdan ustundir."},
    {"arabic": "اَلْمُسْلِمُ مَنْ سَلِمَ النَّاسُ مِنْ يَدِهِ وَلِسَانِهِ", "latin": "Al-muslimu man saliman-naasu min yadihi va lisaanihi.", "cyrillic": "Ал-муслиму ман салиман-наасу мин ядиҳи ва лисааниҳи.", "uzbek": "Musulmon kishi – odamlar uning tili va qo'lidan omonlik topgan kishidir."},
    {"arabic": "لاَ يَدْخُلُ الْجَنَّةَ نَمَّامٌ", "latin": "Laa yadxulul jannata nammaam.", "cyrillic": "Лаа ядхулул жанната наммаам.", "uzbek": "Chaqimchi jannatga kirmaydi."},
    {"arabic": "يَدُ اللَّهِ مَعَ الْجَمَاعَةِ", "latin": "Yadullohi ma'al jamaa'ah.", "cyrillic": "Ядуллоҳи маъал жамааъаҳ.", "uzbek": "Allohning qo'li jamoat (birlik) bilandir."},
    {"arabic": "اَلْكِبْرُ بَطَرُ الْحَقِّ وَغَمْطُ النَّاسِ", "latin": "Al-kibru batarul haqqi va ghomtun-naas.", "cyrillic": "Ал-кибру батарул ҳаққи ва ғомтун-наас.", "uzbek": "Kibr – haqni inkor qilish va odamlarni mensimaslikdir."},
    {"arabic": "اَلْمَرْءُ مَعَ مَنْ أَحَبَّ", "latin": "Al-mar'u ma'a man ahabba.", "cyrillic": "Ал-мар-у маъа ман аҳабба.", "uzbek": "Kishi o'zi sevgan kishisi bilandir."},
    {"arabic": "اَلدُّنْيَا سِجْنُ الْمُؤْمِنِ وَجَنَّةُ الْكَافِرِ", "latin": "Ad-dunyaa sijnul mu'mini va jannatul kaafir.", "cyrillic": "Ад-дуняа сижнул мўмини ва жаннатул каафир.", "uzbek": "Dunyo mo'min uchun qamoqxona, kofir uchun esa jannatdir."},
    {"arabic": "مَنْ حَفَرَ حُفْرَةً لِأَخِيهِ وَقَعَ فِيهَا", "latin": "Man hafara hufratan li-axiihi vaqa'a fiiha.", "cyrillic": "Ман ҳафара ҳуфратан ли-ахийҳи вақаъа фийҳа.", "uzbek": "Kim birodariga chuqur qazisa, o'zi shunga yiqiladi."},
    {"arabic": "لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ", "latin": "Laa yu'minu ahadukum hattaa yuhibba li-axiihi maa yuhibbu li-nafsihi.", "cyrillic": "Лаа юъмину аҳадукум ҳаттаа юҳибба ли-ахийҳи маа юҳиббу ли-нафсиҳи.", "uzbek": "O'ziga ravo ko'rganini birodariga ham ravo ko'rmaguncha iymoningiz komil bo'lmaydi."},
    {"arabic": "اَلْغِيَبَةُ أَشَدُّ مِنَ الزِّنَا", "latin": "Al-ghiybatu asyaddu minaz-zinaa.", "cyrillic": "Ал-ғийбату ашадду миназ-зинаа.", "uzbek": "G'iybat zinodan ham yomondir."},
    {"arabic": "لاَ تَحْقِرَنَّ مِنَ الْمَعْرُوفِ شَيْئًا", "latin": "Laa tahqironna minal ma'ruufi shay-aa.", "cyrillic": "Лаа таҳқиронна минал маърувфи шай-аа.", "uzbek": "Yaxshilikning hech qaysisini kamsitma."},
    {"arabic": "اَلْعَفْوُ عِنْدَ الْمَقْدِرَةِ", "latin": "Al-'afvu 'indal maqdoroh.", "cyrillic": "Ал-афву ъиндал мақдороҳ.", "uzbek": "Qodir bo'lgan paytda kechirimli bo'lish (ulug'likdir)."},
    {"arabic": "اَلْخُلُقُ الْحَسَنُ جِمَالُ الإِنْسَانِ", "latin": "Al-xuluqul hasanu jimaalul insaan.", "cyrillic": "Ал-хулуқул ҳасану жимаалул инсаан.", "uzbek": "Go'zal xulq insonning ko'rkidir."},
    {"arabic": "اَلْجَارُ قَبْلَ الدَّارِ", "latin": "Al-jaaru qoblad-daar.", "cyrillic": "Ал-жаару қоблад-даар.", "uzbek": "Uy olishdan oldin qo'shni tanla."},
    {"arabic": "إِذَا حَكَمْتُمْ فَاعْدِلُوا", "latin": "Izaa hakamtum fa'diluu.", "cyrillic": "Изаа ҳакамтум фаъдилуу.", "uzbek": "Hukm qilsangiz, adolat qiling."},
    {"arabic": "اَلْمَجَالِسُ بِالأَمَانَةِ", "latin": "Al-majaalisu bil-amaanah.", "cyrillic": "Ал-мажаалису бил-амаанаҳ.", "uzbek": "Majlislar (suhbatlar) omonatdir."},
    {"arabic": "اَلصِّدْقُ يَنْفَعُ صَاحِبَهُ", "latin": "As-sidqu yanfa'u soahibahu.", "cyrillic": "Ас-сидқу янфаъу соаҳибаҳу.", "uzbek": "Rostgo'ylik egasiga foyda beradi."},
    {"arabic": "مَنْ لَمْ يَرْحَمْ لَمْ يُرْحَمْ", "latin": "Man lam yarham lam yurham.", "cyrillic": "Ман лам ярҳам лам юрҳам.", "uzbek": "Rahm qilmagan rahm ko'rmaydi."},
    {"arabic": "اَلْإِسْلاَمُ يَعْلُو وَلاَ يُعْلَى عَلَيْهِ", "latin": "Al-Islaamu ya'luu va laa yu'laa 'alayh.", "cyrillic": "Ал-Ислааму яълуу ва лаа юълаа ъалайҳ.", "uzbek": "Islom oliydir, undan ustun narsa yo'q."},
    {"arabic": "اَلْعَدْلُ أَسَاسُ الْمُلْكِ", "latin": "Al-'adlu asaasul mulk.", "cyrillic": "Ал-адлу асаасул мулк.", "uzbek": "Adolat davlatning asosidir."},
    {"arabic": "اَلْأَمَانَةُ رِفْعَةٌ", "latin": "Al-amaanalu rif'ah.", "cyrillic": "Ал-амаанату рифъаҳ.", "uzbek": "Omonatdorlik martabani ko'taradi."},
    {"arabic": "صِلَةُ الرَّحِمِ تَزِيدُ فِي الْعُمُرِ", "latin": "Silatur-rohimi taziidu fil 'umur.", "cyrillic": "Силатур-роҳими тазийду фил ъумур.", "uzbek": "Qarindoshlik aloqalarini bog'lash umrni uzaytiradi."},
    {"arabic": "لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ", "latin": "Laysash-shadiidu bis-suro'ah.", "cyrillic": "Лайсаш-шадийду бис-суръаҳ.", "uzbek": "Kuchli odam – raqibini yiqitgan emas (balki g'azablanganda o'zini tutgan)."},
    {"arabic": "مَنْ تَوَاضَعَ لِلَّهِ رَفَعَهُ", "latin": "Man tavaado'a lillaahi rofa'ahu.", "cyrillic": "Ман таваадоъа лиллааҳи рофаъаҳу.", "uzbek": "Kim Alloh uchun tavozu qilsa, Alloh uni ko'taradi."},
    {"arabic": "اَلْخَجَلُ مِنَ الْإِيمَانِ", "latin": "Al-xajalu minal iimaan.", "cyrillic": "Ал-хажалу минал иймаан.", "uzbek": "Hayo imondandir."},
    {"arabic": "طَلَبُ الْعِلْمِ فَرِيضَةٌ", "latin": "Tolabul 'ilmi fariiroh.", "cyrillic": "Толабул илми фарийроҳ.", "uzbek": "Ilm izlash farzdir."},
    {"arabic": "لاَ حَيَاةَ مَعَ الْيَأْسِ", "latin": "Laa hayaata ma'al ya's.", "cyrillic": "Лаа ҳаяата маъал яъс.", "uzbek": "Umidsizlik bilan hayot bo'lmaydi."},
    {"arabic": "اَلصَّبْرُ يُورِثُ النَّصْرَ", "latin": "As-sobru yuoritsun-nasr.", "cyrillic": "Ас-собру юорицун-наср.", "uzbek": "Sabr g'alabani keltirur."},
    {"arabic": "اَلنَّظَرُ إِلَى الْكَعْبَةِ عِبَادَةٌ", "latin": "An-nazoru ilal Ka'bati 'ibaadah.", "cyrillic": "Ан-назору илал Каъбати ибаадаҳ.", "uzbek": "Ka'baga nazar solish ibodatdir."},
    {"arabic": "اَلْعَمَلُ بِلاَ إِخْلاصٍ لاَ يُقْبَلُ", "latin": "Al-'amalu bilaa ixloosin laa yuqbal.", "cyrillic": "Ал-амалу билаа ихлоосин лаа юқбал.", "uzbek": "Ixlossiz qilingan amal qabul bo'lmaydi."},
    {"arabic": "اَلْحَسَدُ يَأْكُلُ الْحَسَنَاتِ", "latin": "Al-hasadu ya'kulul hasanaat.", "cyrillic": "Ал-ҳасаду яъкулул ҳасанаат.", "uzbek": "Hasad yaxshiliklarni yeb bitiradi."},
    {"arabic": "اَلْقُرْآنُ رَبِيعُ الْقُلُوبِ", "latin": "Al-Qur'aanu rabii'ul quluub.", "cyrillic": "Ал-Қур-аану рабийъул қулууб.", "uzbek": "Qur'on qalblar bahoridir."},
    {"arabic": "اَلْأَمَانَةُ تُرْضِي اللَّهَ", "latin": "Al-amaanatu turdil-lah.", "cyrillic": "Ал-амаанату турдил-лаҳ.", "uzbek": "Omonatdorlik Allohni rozi qiladi."},
    {"arabic": "مَنْ صَبَرَ ظَفِرَ", "latin": "Man sobara zofir.", "cyrillic": "Ман собара зофир.", "uzbek": "Kim sabr qilsa, zafar topadi."},
    {"arabic": "اَلْخُلُقُ الْكَرِيمُ رَأْسُ الْعَقْلِ", "latin": "Al-xuluqul kariimu ro'sul 'aql.", "cyrillic": "Ал-хулуқул карийму раъсул ақл.", "uzbek": "Go'zal xulq aqlning boshidir."},
    {"arabic": "اَلْإِنْسَانُ بِعَمَلِهِ لاَ بِقَوْلِهِ", "latin": "Al-insaanu bi'amalihi laa biqavlihi.", "cyrillic": "Ал-инсаану биъамалиҳи лаа биқовлиҳи.", "uzbek": "Inson so'zi bilan emas, amali bilan o'lchanadi."},
    {"arabic": "اَلْفِتْنَةُ أَشَدُّ مِنَ الْقَتْلِ", "latin": "Al-fitnatu asyaddu minal qatl.", "cyrillic": "Ал-фитнату ашадду минал қатл.", "uzbek": "Fitna qotillikdan ham yomondir."},
    {"arabic": "اَلْعُقُولُ مَوَازِينُ الْأَخْلَاقِ", "latin": "Al-'uquulu mavaaziinul axlaaq.", "cyrillic": "Ал-уқуулу маваазийнул ахлаақ.", "uzbek": "Aql axloqning tarozisidir."},
    {"arabic": "لاَ تَؤُخِّرْ عَمَلَ الْيَوْمِ إِلَى الْغَدِ", "latin": "Laa tu'axxir 'amalal yavmi ilal ghod.", "cyrillic": "Лаа туъаххир ъамалал явми илал ғод.", "uzbek": "Bugungi ishni ertaga qoldirma."},
    {"arabic": "اَلْوَعْدُ دَيْنٌ", "latin": "Al-va'du dayn.", "cyrillic": "Ал-ваъду дайн.", "uzbek": "Vada – qarzdir."},
    {"arabic": "اَلسَّكُوتُ عَلَى الْخَطَأِ خَطَأٌ", "latin": "As-sakuutu 'alal xoto'i xoto'un.", "cyrillic": "Ас-сакууту ъалал хато-и хато-ун.", "uzbek": "Xatoga sukut saqlash – o'zi xatodir."},
    {"arabic": "اَلْإِصْلاَحُ بَيْنَ النَّاسِ أَفْضَلُ الْعِبَادَاتِ", "latin": "Al-islaahu baynan-naasi afdolul 'ibaadaat.", "cyrillic": "Ал-ислааҳу байнан-нааси афдолул ъибаадаат.", "uzbek": "Odamlar o'rtasini isloh qilish – eng afzal ibodatdir."},
    {"arabic": "اَلْحَقُّ يَعْلُو وَلاَ يُعْلَى عَلَيْهِ", "latin": "Al-haqqu ya'luu va laa yu'laa 'alayh.", "cyrillic": "Ал-ҳаққу яълуу ва лаа юълаа ъалайҳ.", "uzbek": "Haqiqat oliydir, undan ustun narsa yo'q."},
    {"arabic": "مَنْ لَمْ يَرْحَمِ الصَّغِيرَ فَلَيْسَ مِنَّا", "latin": "Man lam yarhamis-soghiirol falaysa minnaa.", "cyrillic": "Ман лам ярҳамис-соғийрол фалайса миннаа.", "uzbek": "Kichiklarga rahm qilmagan kishi bizdan emas."},
    {"arabic": "اَلطَّعَامُ بَرَكَةٌ", "latin": "At-ta'aamu barakah.", "cyrillic": "Ат-таъааму барака.", "uzbek": "Taom barakadir."},
    {"arabic": "اَلْعِلْمُ صَيْدٌ وَالْكِتَابَةُ قَيْدٌ", "latin": "Al-'ilmu soydun val-kitaabatu qoydun.", "cyrillic": "Ал-илму сойдун вал-китаабату қойдун.", "uzbek": "Ilm ovdir, yozib qo'yish esa uni bog'lab qo'yishdir."},
    {"arabic": "اَلصِّدْقُ خَيْرٌ مِنَ الْكَذِبِ", "latin": "As-sidqu xoyrun minal kazib.", "cyrillic": "Ас-сидқу хойрун минал казиб.", "uzbek": "Rostgo'ylik yolg'ondan yaxshiroqdir."},
    {"arabic": "اَلْأَدَبُ زِينَةُ الْإِنْسَانِ", "latin": "Al-adabu ziinatulis-insaan.", "cyrillic": "Ал-адабу зийнатул-инсаан.", "uzbek": "Odob insonning ziynatidir."},
    {"arabic": "اَلنَّظَافَةُ مِنَ الْإِيمَانِ", "latin": "An-nazofatu minal iimaan.", "cyrillic": "Ан-назофату минал иймаан.", "uzbek": "Poklik imondandir."},
    {"arabic": "يَدُ اللَّهِ مَعَ الْجَمَاعَةِ", "latin": "Yadullohi ma'al jamaa'ah.", "cyrillic": "Ядуллоҳи маъал жамааъаҳ.", "uzbek": "Allohning qo'li jamoat bilandir."},
    {"arabic": "اَلْحِلْمُ سَيِّدُ الْأَخْلَاقِ", "latin": "Al-hilmu sayyidul axlaaq.", "cyrillic": "Ал-ҳилму саййидул ахлаақ.", "uzbek": "Muloyimlik xulq-atvorning sayyididir."},
    {"arabic": "مَنْ أَرَادَ الْعِزَّ فَلْيُطِعِ اللَّهَ", "latin": "Man araadal 'izza falyuti'illah.", "cyrillic": "Ман араадал ъизза фальютиъиллаҳ.", "uzbek": "Kim izzat (obro') xohlasa, Allohga itoat etsin."},
    {"arabic": "اَلْعِلْمُ فِي الصِّغَرِ كَالنَّقْشِ فِي الْحَجَرِ", "latin": "Al-'ilmu fis-sighori kannaqshi fil hajar.", "cyrillic": "Ал-илму фис-сиғори каннақши фил ҳажар.", "uzbek": "Yoshlikdagi ilm – toshga o'yilgan naqsh kabidir."},
    {"arabic": "اَلْأَمَلُ حَيَاةٌ", "latin": "Al-amalu hayaah.", "cyrillic": "Ал-амалу ҳаяаҳ.", "uzbek": "Umid – hayotdir."},
]
